/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;

import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spMain = new javax.swing.JSplitPane();
        spTrai = new javax.swing.JPanel();
        btKhachHang = new javax.swing.JButton();
        btThuePhong = new javax.swing.JButton();
        btPhong = new javax.swing.JButton();
        btDichVu = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btChiTietPhong = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();
        spPhai = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        spTrai.setBackground(new java.awt.Color(153, 255, 153));

        btKhachHang.setBackground(new java.awt.Color(255, 255, 0));
        btKhachHang.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btKhachHang.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\customer1.png")); // NOI18N
        btKhachHang.setText("Khách Hàng");
        btKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKhachHangMouseClicked(evt);
            }
        });

        btThuePhong.setBackground(new java.awt.Color(255, 255, 0));
        btThuePhong.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btThuePhong.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\rent1.png")); // NOI18N
        btThuePhong.setText("Thuê Phòng");
        btThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThuePhongMouseClicked(evt);
            }
        });

        btPhong.setBackground(new java.awt.Color(255, 255, 0));
        btPhong.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btPhong.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\room11.png")); // NOI18N
        btPhong.setText("Phòng");
        btPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPhongMouseClicked(evt);
            }
        });

        btDichVu.setBackground(new java.awt.Color(255, 255, 0));
        btDichVu.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btDichVu.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\service1.png")); // NOI18N
        btDichVu.setText("Dịch Vụ");
        btDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDichVuMouseClicked(evt);
            }
        });

        btHoaDon.setBackground(new java.awt.Color(255, 255, 0));
        btHoaDon.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btHoaDon.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\bill1.png")); // NOI18N
        btHoaDon.setText("Hóa Đơn");
        btHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHoaDonMouseClicked(evt);
            }
        });

        btChiTietPhong.setBackground(new java.awt.Color(255, 255, 0));
        btChiTietPhong.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btChiTietPhong.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\icon\\icon\\ctroom1.png")); // NOI18N
        btChiTietPhong.setText("Chi Tiết Phòng");
        btChiTietPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btChiTietPhongMouseClicked(evt);
            }
        });

        btDangXuat.setBackground(new java.awt.Color(255, 255, 0));
        btDangXuat.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        btDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icon\\logout.png")); // NOI18N
        btDangXuat.setText("Đăng Xuất");
        btDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout spTraiLayout = new javax.swing.GroupLayout(spTrai);
        spTrai.setLayout(spTraiLayout);
        spTraiLayout.setHorizontalGroup(
            spTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spTraiLayout.createSequentialGroup()
                .addGroup(spTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btThuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spTraiLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btChiTietPhong))
                    .addComponent(btDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        spTraiLayout.setVerticalGroup(
            spTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spTraiLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btChiTietPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        spMain.setLeftComponent(spTrai);

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\icon\\main.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout spPhaiLayout = new javax.swing.GroupLayout(spPhai);
        spPhai.setLayout(spPhaiLayout);
        spPhaiLayout.setHorizontalGroup(
            spPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 982, Short.MAX_VALUE)
        );
        spPhaiLayout.setVerticalGroup(
            spPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spPhaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        spMain.setRightComponent(spPhai);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("KHÁCH SẠN DDH HOME");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icon\\hotel3.png")); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icon\\house1.png")); // NOI18N
        jLabel2.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMain, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKhachHangMouseClicked
      frmKhachHang frm = new frmKhachHang(spMain, spPhai);
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btKhachHangMouseClicked

    private void btThuePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThuePhongMouseClicked
        frmThuePhong frm = new frmThuePhong(spMain, spPhai);
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btThuePhongMouseClicked

    private void btPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPhongMouseClicked
      frmPhong frm = new frmPhong(spMain, spPhai);
        spMain.setRightComponent(frm);
        
    }//GEN-LAST:event_btPhongMouseClicked

    private void btDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDichVuMouseClicked
        frmDichVu frm = new frmDichVu(spMain, spPhai);
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btDichVuMouseClicked

    private void btHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHoaDonMouseClicked
        frmHoaDon frm = new frmHoaDon(spMain, spPhai);
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btHoaDonMouseClicked

    private void btChiTietPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChiTietPhongMouseClicked
      frmChiTietPhong frm = new frmChiTietPhong(spMain, spPhai);
        spMain.setRightComponent(frm);
    }//GEN-LAST:event_btChiTietPhongMouseClicked

    private void btDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangXuatMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChiTietPhong;
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btDichVu;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btKhachHang;
    private javax.swing.JButton btPhong;
    private javax.swing.JButton btThuePhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane spMain;
    private javax.swing.JPanel spPhai;
    private javax.swing.JPanel spTrai;
    // End of variables declaration//GEN-END:variables
}
